---
GameServerIp: "127.0.0.1"
GameServerApiPort: 22345
PlayerUpdateIntervalInSeconds: 1

FactionPlayfieldKickerMod:
  BootMessage: "You are not allowed to enter this faction's playfield."
  
  # key is the faction id (or player id if not in a faction)
  # -1 means any player that doesn't match any other entry.
  # FromPlayfield can be left out to let people go from any playfield
  FactionHomeWorlds:
    "Akua Orbit": 712


StructureOwnershipMod:
  CaptureRewardMinutes: 0.1
  EntityCaptureItems:
  - EntityId: 120001
    CaptureRewardMinutes: 0.5
    RewardItemStacks:
    - Id: 2274
      Amount: 1
    - Id: 2276
      Amount: 2

SellToServerMod:
  SellLocations:
  - BoundingBox:
      Playfield: Akua2
      Rect:
        pt0:
          x: -1434
          y: 48
          z: 700
        pt1:
          x: -1430
          y: 51
          z: 701.5
    ItemIdToUnitPrice:
      2415: 1
      2413: 0.1
    DefaultPrice: 1.0

  - BoundingBox:
      Playfield: Akua2
      Rect:
        pt0:
          x: -1439
          y: 49
          z: 707.5
        pt1:
          x: -1437.7
          y: 51
          z: 710
    ItemIdToUnitPrice:
      2415: 1
      2413: 100
