---
BuyShipCommand: "/buyship"
ShipSellers:
- Name: Bob
  Origin: 1
  BoundingBox:
    Playfield: Akua2
    Rect:
      min:
        x: -1434
        y: 48
        z: 700
      max:
        x: -1430
        y: 51
        z: 701.5
  ShipsForSale:
  - DisplayName: Ship One
    BlueprintName: SV_PF1   # Name of a file (minus extension) from the Content\Prefabs folder
    EntityType: SV
    ShipNameFormat: "Cool ship1 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 100.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
  - DisplayName: Ship Two
    BlueprintName: SV_PF2
    EntityType: CV
    ShipNameFormat: "Cool ship2 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 2000.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
- Name: Bobby
  Origin: -1   # -1 means any player can buy
  BoundingBox:
    Playfield: Akua2
    Rect:
      min:
        x: -1439
        y: 49
        z: 707.5
      max:
        x: -1437.7
        y: 51
        z: 710
  ShipsForSale:
  - DisplayName: Shipp One
    BlueprintName: SV_PF1
    EntityType: SV
    ShipNameFormat: "Cool ship1 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 100.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
  - DisplayName: Shipp Two
    BlueprintName: SV_PF2
    EntityType: CV
    ShipNameFormat: "Cool ship2 for {0}"
    MessageToShowOnPurchase: "Look outside for your new ship!"
    Price: 2000.50
    SpawnLocation:
      x: -1439
      y: 149
      z: 707.5
