---
GameServerIp: "127.0.0.1"
GameServerApiPort: 22345

PlayfieldStructureRegenMod:
  PlayfieldsToRegenerate:
   "Akua Orbit":
    StructuresIds:
     - 72003
     - 72004
  
   "Omicron":
    StructuresIds:
     - 72003
     - 72004
  