---
GameServerIp: "127.0.0.1"
GameServerApiPort: 12345

TeleportCommand: "/gohome"

# key is the faction id (or player id if not in a faction)
# -1 means any player that doesn't match any other entry.
# FromPlayfield can be left out to let people go from any playfield
FactionHomeWorlds:
 103:
  FromPlayfield: "Akua Orbit"
  ToPlayfield: "Akua2"
  WarpLocations:
   - Position:
      X: 0.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
   - Position:
      X: 150.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
 -1:
  ToPlayfield: "Omicron"
  WarpLocations:
   - Position:
      X: 0.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
