---
GameServerIp: "127.0.0.1"
GameServerApiPort: 22345

TeleportCommand: "/gohome"

# key is the faction id (or player id if not in a faction)
# -1 means any player that doesn't match any other entry.
FactionHomeWorlds:
 102:
  Playfield: "Akua2"
  WarpLocations:
   - Position:
      X: 0.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
   - Position:
      X: 150.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
 -1:
  Playfield: "Omicron"
  WarpLocations:
   - Position:
      X: 0.0
      Y: 150.0
      Z: 0.0
     Rotation:
      X: 0.0
      Y: 0.0
      Z: 0.0
