---
GameServerIp: "127.0.0.1"
GameServerApiPort: 22345
PlayerUpdateIntervalInSeconds: 1

SellLocations:
- BoundingBox:
    Playfield: Akua2
    Rect:
      pt0:
        x: -1434
        y: 48
        z: 700
      pt1:
        x: -1427
        y: 51
        z: 701
  ItemIdToUnitPrice:
    2415: 1
    2413: 0.1
- BoundingBox:
    Playfield: Akua2
    Rect:
      pt0:
        x: 0
        y: 6
        z: 9
      pt1:
        x: 1
        y: 2.6
        z: 5
  ItemIdToUnitPrice:
    2415: 1
    2413: 0.1
