GameServerIp: "127.0.0.1"
GameServerApiPort: 22345

EntityToCapture: 72001
CaptureRewardMinutes: 0.5

EntityCaptureItems:
- EntityId: 72001
  CaptureRewardMinutes: 0.5
  RewardItemStacks:
  - Id: 2274
    Amount: 1
  - Id: 2276
    Amount: 2
